### ISSUE TITLE
Register Link showing even when option not selected

### ISSUE THREAD

**Issue by danaskallman** [christianwach/civicrm-event-organiser#10]
The Register link appears on Events even when not selected. Can that be changed?

This is what it looks like:
![register-link-shows-even-when-not-checked](https://cloud.githubusercontent.com/assets/1139085/22603922/40402e58-ea17-11e6-9611-f5f3810d0629.jpg)

Here's the event settings
![eo-civicrm-settings](https://cloud.githubusercontent.com/assets/1139085/22603928/46afeae4-ea17-11e6-8ea1-0f11cbfcd236.jpg)

**Comment by christianwach** [comment]
@danaskallman I have addressed this in aa1685ccffa946978f12d3e0e6162019a2b13e39 - let me know it works for you.

**Comment by danaskallman** [comment]
It seems when I add a new event it doesn't display the Registration Links option, but previously published events still display it. Is there something else I should do?

**Comment by christianwach** [comment]
@danaskallman Can you post a screenshot of what you're seeing and let me know which theme you're using?

**Comment by danaskallman** [comment]
@christianwach it's a genesis theme, here's screenshot

![eo-reg-link-genesis](https://cloud.githubusercontent.com/assets/1139085/24659762/b02e5784-191b-11e7-90ef-8271f04109e1.jpg)

When I inspect element it's the same `civicrm-event-register-links` class as other sites that don't have a genesis theme.

**Comment by christianwach** [comment]
@danaskallman Ah, okay. I believe CiviCRM won't return a link if the event has finished. Can you try this on a current or future event?

**Comment by danaskallman** [comment]
@christianwach yes, with a new event that I don't make any civievent selections it doesn't show up. 

However, I also tested adding it and then say changing my mind and removing CiviEvent settings, deselecting the online registration option and even using the delete event from CiviCRM. The Register link remains and event is still in CiviCRM too.

**Comment by christianwach** [comment]
> yes, with a new event that I don't make any civievent selections it doesn't show up.

Thanks @danaskallman - this should be fixed in ec04cd11ce5efda44db9fdab8bc0630b3af4dfd7

> I also tested adding it and then say changing my mind and removing CiviEvent settings, deselecting the online registration option and even using the delete event from CiviCRM. The Register link remains and event is still in CiviCRM too.

The "Delete unused CiviEvents" option doesn't delete CiviEvents unless a sequence has been changed in EO. The use case is, for example, where you change your schedule from "daily" to "weekly" and you want to delete the CiviEvents that are not part of the new sequence. It is an option because you may not want to do that - e.g. perhaps the existing CiviEvents have data you want to keep.

But it's a good point in a different sense: i.e. there's currently no way to sever the link between the EO events and the CiviEvents. I'm wondering why one might want to do that. Any thoughts?

**Comment by danaskallman** [comment]
> But it's a good point in a different sense: i.e. there's currently no way to sever the link between the EO events and the CiviEvents. I'm wondering why one might want to do that. Any thoughts?

Not sure, just was trying to get the Register link to disappear. Not sure it would be happen often, but maybe initial conversations are lets have folks register but then change there mind. Not huge issue at all.

**Comment by christianwach** [comment]
> lets have folks register but then change there mind

I think the latest commit allows you to switch off the Registration Link for any event. For non-repeating events, it can be done wither in EO or Civi. For repeating events, it can be done globally for the whole sequence in the EO event edit page - or per CiviEvent in CiviCRM's back end.

**Comment by christianwach** [comment]
@danaskallman I think it might be time that new issues are opened which are more specific - I'm pretty sure the original issue here has been resolved!
