### ISSUE TITLE
Plugin activation error

### ISSUE THREAD

**Issue by richardsplayground** [christianwach/civicrm-event-organiser#11]
Hi

New wordpress 4.7.3 install
CiviCRM 4.7.18
Event Organiser plugin 3.1.9
CiviCRM Event Organiser plugin downloaded from Github as a zip file on 2017-4-11.

Activating the plugin triggers a fatal error:
Fatal error: Redefinition of parameter $event_data in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/civicrm-event-organiser-master/includes/civicrm-event-organiser-eo.php on line 235

Any ideas how to resolve this?

Thank you so much

**Comment by christianwach** [comment]
@richardsplayground Thanks for the report. Which version of PHP are you running? 

You can download the zip of the master branch which contains a fix for the fatal error. Please let me know if you find further issues.

**Comment by richardsplayground** [comment]
This totally resolved the error.  Thank you so much!

I am on PHP 7.0.16.

Thanks again.
