### ISSUE TITLE
Editing an existing event causes 500 error

### ISSUE THREAD

**Issue by kcristiano** [christianwach/civicrm-event-organiser#17]
Versions:
WP 4.8.2  CiviCRM 4.7.24  php 5.6.31 apache 2.4 EO 3.4.0 Civicrm-event-organiser 0.4

Steps to reproduce:
Create an Event in Event Organiser
Choose Sync with CiviCRM, Enable Registration

Event syncs correctly.

Edit the event and change the date
Receive WSOD

Only error is 
```
PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /webroot/wp-content/plugins/civicrm/civicrm/CRM/Core/DAO/AllCoreTables.php on line 261
```
It seems that the process is hanging and dies when the max execution timeout is reached.

**Comment by christianwach** [comment]
@kcristiano Thanks for catching this. I've been trying to figure out what changed - I think it may be on the CiviCRM side, but can't be sure. Can you test my update to master?

**Comment by kcristiano** [comment]
@christianwach tested and it is working EO-->CiviCRM as long as the sync event box is checked.

It also works CiviCRM --> EO

Thanks for getting on this so quickly.

**Comment by christianwach** [comment]
> as long as the sync event box is checked

Just to be clear - is there a situation where this occurs when Sync is *not* checked?

**Comment by kcristiano** [comment]
In my testing I always have to check the box on update EO --> CiviCRM.   I am not certain that is necessary, just what I have done.  That checkbox is showimg unchecked at all times, so I check it.

**Comment by christianwach** [comment]
@kcristiano Okay, gotcha. I'll consider this fixed then :)
