### ISSUE TITLE
New Event Types of same name after a second or third manual sync 

### ISSUE THREAD

**Issue by danaskallman** [christianwach/civicrm-event-organiser#19]
When new EO Event Categories are added and then a manual sync is done again, after the initial setup, it seems new Event Types with their own ID are created, see screenshot. 

![eo-civi-sync-creates-new-event-types](https://user-images.githubusercontent.com/1139085/31743083-cdc6e3c2-b427-11e7-8511-1659986d51e1.png)

More categories were added, so we did another manual sync and repeat event types where shown with unique IDs. Can this be prevented?

**Comment by christianwach** [comment]
@danaskallman I can't seem to replicate this locally. Are you sure you have a version of the plugin after 40295d23e28495a5adb5c62633bc6c9bb4383d37 which IIRC solved this? If you do have the most recent version, then are there steps to replicate?

**Comment by christianwach** [comment]
FWIW, the only way I have found to break taxonomy sync is if I change the `Label` of the Event Type in CiviCRM and then sync from EO to CiviCRM -  another reason to manage Categories in EO and leave them alone in CiviCRM.

**Comment by danaskallman** [comment]
Hmmm, I wonder if that's it. The client is editing that I believe, but changing the name in EO never in Civi, since they don't have access to that.

**Comment by christianwach** [comment]
@danaskallman Closing this as I seem to recall that we fixed this. Please feel free to reopen if I'm mistaken.
