### ISSUE TITLE
Ability to Copy Existing event and copies all Civi tab settings too

### ISSUE THREAD

**Issue by danaskallman** [christianwach/civicrm-event-organiser#21]
When using CiviEvent you can copy an event and it copies all settings like profiles, fees, text and repeat events and the like for the new event, so you just need to edit the time/date for mostly. Is there a way to do that from CEO so events get created in CiviEvent, but the extra settings in CiviEvent don't have to be manually re-setup by admin staff?

**Comment by kcristiano** [comment]
A use case we've come up with is Organizations with detailed repeating events.  They can use a template or simply copy the event in CiviCRM and all of the settings and text are populated.  They only have to set the dates, the repeat parameters and any text changes.   

This allows profile selection, receipts and confirmations to be duplicated quite easily.

However, when the event syncs - only the first event syncs and a manual sync is then needed.

If we start in EO and create a repeating event it creates separate events in CiviCRM - this is fine, but we still have to configure all other settings.  

If the Copy worked for  CEO (Currently the links are to the event we copied as opposed to a new one) this would be a great improvement.
