### ISSUE TITLE
Network activating removes settings page and prompts notice

### ISSUE THREAD

**Issue by andyburnsco** [christianwach/civicrm-event-organiser#22]
If you network activate this plugin on multisite, it removes the settings link under settings and prompts an erroneous nag 

![civi-eo-settings](https://user-images.githubusercontent.com/18341942/50310425-8cb00800-0467-11e9-8c49-7bc79e31f27f.PNG)

The link location does not work and the path does not make sense.

For now, it seems it should not be network activated.

**Comment by christianwach** [comment]
@andyburnsco On re-reading what you wrote, I'm not clear how you activated this plugin. 

Did you:

1. activate it on a single site first and later network-activate it?
2. network-activate it to begin with?

Additionally:

* is Event Organiser network-activated?
* is CiviCRM network-activated?

**Comment by christianwach** [comment]
FWIW, I generally advise that this plugin should be activated at the same "level" as Event Organiser - i.e. 

* if Event Organiser is network-activated, then network-activate this plugin.
* if Event Organiser is activated on individual sites, then do the same with this plugin.

The same goes for the Radio Buttons for Taxonomies plugin.

**Comment by christianwach** [comment]
One more note: in my opinion, network-activating Event Organiser and CiviCRM Event Organiser is an unlikely scenario. A couple of reasons:

* Event Organiser doesn't provide a Network Admin settings screen, which implies that it's happiest being activated on individual sites.
* Similarly, CiviCRM Event Organiser's settings screen doesn't make a great deal of sense when network-activated: for example, which site would Manual Sync be syncing to? (It's the main site, of course, but then how would one sync to a sub-site?)

So then, 29bfb5834caaf075fc0cc7d31e93613f64c7d92c should prevent network-activation as well as alleviate confusion.
