### ISSUE TITLE
Syncing - one way?

### ISSUE THREAD

**Issue by bradydan** [christianwach/civicrm-event-organiser#3]
Just getting started with this plugin, I have a few questions.

Syncing implies two-way. We only really want:

1. One-way syncing (CiviEvent —> WP Event Organiser)
2. Some WordPress-only events to be created in Events Organiser and left untouched by CiviCRM

Is this possible?

Also, now that WooDojo has been deprecated, [and I notice that it's no longer a requirement](https://github.com/christianwach/civicrm-event-organiser/issues/2#issuecomment-140507955), is there a replacement for the HTML descriptions on categories? A quick search brought back this plugin: [Allow HTML in Category Descriptions](https://en-gb.wordpress.org/plugins/allow-html-in-category-descriptions/) but perhaps your plugin only works with WooDojo?

We're on:
* Civi 4.6.11
* WP 4.4.1
* Event Organiser 2.13.7 

Thanks

**Comment by christianwach** [comment]
> Syncing implies two-way. We only really want: [snip]

@bradydan That's a big question! I'll think it through on Monday.

> now that WooDojo has been deprecated, and I notice that it's no longer a requirement, is there a replacement for the HTML descriptions on categories?

The plugin contains a replacement for WooDojo and no longer needs it. See 4a7ab729669986eed80735f67c95aebc0ecd1f09. I must have forgotten to update the documentation.

**Comment by bradydan** [comment]
Thanks, is this requirement still correct?

> the custom WordPress.php hook file from the CiviCRM Hook Tester repo on GitHub installed so that it overrides the built-in CiviCRM hook file.

**Comment by christianwach** [comment]
Only for CiviCRM versions prior to 4.6.

**Comment by bradydan** [comment]
Thanks :)

You may want to update the documentation

**Comment by christianwach** [comment]
This plugin is low priority for me which is why it's not in the WordPress plugin directory. The biggest roadblock is CiviCRM's handling of repeating events - which is one reason this plugin prioritises a workflow based on creating events in EO and then (optionally) passing them over to CiviCRM when published.

**Comment by bradydan** [comment]
Thanks for the workflow hint. I'll see how we get on with this. 

Understood about the low priority. I'm prepared to pay you for some consultancy time to get us up and running.

**Comment by christianwach** [comment]
@bradydan That sounds great - let's arrange something by email.

**Comment by bradydan** [comment]
Thanks for updating the docs and all your other help :+1:
