### ISSUE TITLE
Manual Sync of Event Organiser Venues with CiviCRM Locations Hangs

### ISSUE THREAD

**Issue by andyburnsco** [christianwach/civicrm-event-organiser#34]
I tried doing a manual sync on an existing install and it did not process. Did not expect success but wanted to test how this would work on existing install given the disclaimer on that screen. The result is the metabox now shows as this:

![image](https://user-images.githubusercontent.com/18341942/174322959-77aeb772-f7a1-4693-8715-b0e012cfcc02.png)

Selecting "stop sync" bounces to CiviCRM Event Organiser settings page. Deactivating / reactivating plugin does not resolve. Thoughts? Is there a a setting in wp_options to manually alter? Looks like it isn't hurting anything.

CEO: Version 0.7.2a
Civi 5.50.1

**Comment by andyburnsco** [comment]
I reverted to an older version of the plugin 0.4.3, clicked stop sync, and it saved successfully.

Yes, 0.4.3, was reliable and did the job for a loooong time :)

**Comment by christianwach** [comment]
@andyburnsco Sounds like you have a Javascript error. What you're seeing is intentional - it's the UI for stepping through the sync process when Javascript is disabled.

**Comment by andyburnsco** [comment]
I didn't see any JS errors in the console. All good.
