### ISSUE TITLE
Settings not saving (or maybe just not showing as saved)

### ISSUE THREAD

**Issue by judgej** [christianwach/civicrm-event-organiser#4]
It says "Settings Saved" but the synchronisation settings remain unchecked.

I'm working on this clone here, with no custom changes yet:

https://github.com/academe/civicrm-event-organiser

Trying to sync CiviCRM to EO.

Plugin directory is `civicrm-event-organiser`.

**Comment by christianwach** [comment]
Yeah, sorry about that. It's catch-all feedback whenever the form is submitted. Was on my to-do list to refine this.

**Comment by judgej** [comment]
Do the settings still get applied, even if not shown when going back in? If so, it won't hold me back in the meantime.

**Comment by christianwach** [comment]
The sync checkboxes aren't settings as such - you check a box, it then performs that sync when the form is submitted. Not great UI or UX, but it wasn't a priority. Perhaps it should be now.

**Comment by christianwach** [comment]
It would probably be better to split the sync stuff off to a separate sub-page the way I do in the Civi Member Sync plugin. But time, resources, etc etc

**Comment by christianwach** [comment]
As a temporary measure, 1df50086c4129660751d84e6b773e53d82d8fe38 adds explanatory text about the sync procedures to the admin screen. Hope this helps.
