### ISSUE TITLE
Cannot create an event for a venue that maps to the slug of another event

### ISSUE THREAD

**Issue by judgej** [christianwach/civicrm-event-organiser#5]
I need to reproduce this, so will be digging a little deeper to see what the real issue is.

This is just Civi to EO at his time.

My understanding is that two different locations on Civi can result in the same location slug on EO. Civi thinks it is creating a new location on EO, but the slugs clash and the event does not sync. I'm not sure how much does and does not sync.

**Comment by judgej** [comment]
One thing I'm not clear about, is exactly when synchronising happens. Is it instantly the Civi event is saved, or does it get queued? Or (more likely) is it a scheduled process that scans all events at both ends to determine what needs to be updated?

**Comment by judgej** [comment]
Okay, spotted the `civi_wp_member_sync_refresh` scheduled event which is scheduled to run once a day. I have seen events sync across instantly, so what else is pulling them across?

**Comment by judgej** [comment]
So I understand, does the Civi WP connector plugin create filter and action hooks so that WP plugins can be directly triggered on Civi actions?

**Comment by christianwach** [comment]
> My understanding is that two different locations on Civi can result in the same location slug on EO. Civi thinks it is creating a new location on EO, but the slugs clash and the event does not sync. I'm not sure how much does and does not sync.

Since my updates yesterday, the event should still be created, though [the venue will not](https://github.com/christianwach/civicrm-event-organiser/blob/master/civicrm-event-organiser-eo-venue.php#L328) be created and the EO event will be left without a venue.

> I have seen events sync across instantly, so what else is pulling them across?

Nothing is "pulling them across" as such :-) The plugin [registers callbacks for the relevant hooks](https://github.com/christianwach/civicrm-event-organiser/blob/master/civicrm-event-organiser-civi.php#L64-L66) and proceeds from there.

The reason CiviCRM WP Member Sync uses scheduled events is that Civi memberships are usually updated via cron (genuine cron rather than WordPress pseudo-cron), after which WordPress needs to register that this has taken place. Other amends to CiviCRM memberships are "instant" too, in that they are triggered by the relevant CiviCRM hooks.

Hope that helps.

**Comment by christianwach** [comment]
> Civi WP connector plugin create filter and action hooks so that WP plugins can be directly triggered on Civi actions?

No, that is now obsolete since it has been included [in CiviCRM core](https://github.com/civicrm/civicrm-core/blob/master/CRM/Utils/Hook/WordPress.php) since version 4.6. It needed for versions prior to that.

**Comment by christianwach** [comment]
For more info, see my post on [the CiviCRM site](https://civicrm.org/blogs/haystack/working-civicrm-46-wordpress).

**Comment by judgej** [comment]
Thanks. It looks like Civi and the CRM are integrated a lot tighter than I understood, share each other's code space.

**Comment by christianwach** [comment]
They do now :-)

**Comment by christianwach** [comment]
Though I just noticed that the CiviCRM site has messed up my code examples since they upgraded it. Drupal, eh? *sigh*

**Comment by judgej** [comment]
I noticed all the constructors return `$this`. I'm pretty sure PHP constructors are not supposed to return anything. That might be worth a global change.

**Comment by christianwach** [comment]
> I'm pretty sure PHP constructors are not supposed to return anything.

That's a convention I've used since the days of PHP 4. As I understand it, it doesn't matter what a constructor returns.

**Comment by christianwach** [comment]
But point taken - I can shave a few bytes :-)

**Comment by christianwach** [comment]
> OT: I noticed all the constructors return `$this`.

Fixed in 398ad42203b1b7b6dc020d75affad2091e7ba8ec. Thanks!

**Comment by judgej** [comment]
Thanks - merged in.

**Comment by christianwach** [comment]
I cleaned up a lot of other cruft as well today - you might just want to rebase :-)

**Comment by judgej** [comment]
I've never had a need to rebase before. What would the purpose be in this case? Is it more for documentation/ease of seeing what has changed, by taking changes before a later point out of the pull?

**Comment by christianwach** [comment]
I thought you may have added commits to your branch - but since you haven't, my comment was irrelevant.

**Comment by judgej** [comment]
NP. I know some people live on rebases, and I've never needed to do one, so was curious what I was missing ;-)

**Comment by judgej** [comment]
As usual, a one-line fix after running through 1000 lines to find it :-)

The Problem
------

Event 1 and event 2 have different locations. The location address 1 details happen to result in the same WP slug, but are distinctly unique titles. Examples are:

* Whitley Bay
* Whitley-Bay
* Whitley Bay (this bizarrely too - the contents in these brackets is stripped out by by WP sanitize_title)

When the second event is synced from Civi to EO, this plugin attempts to see if the location already exists in EO. It looks for it in three different ways:

* A Civi ID metafield, put in by a previous sync.
* The exact lat/long reference.
* The exact address 1 match (arguably this one could be misleading).

If any of these match, then the EO location is reused and linked to the new event. If any of these do not match, then a new location is created.

Now, when the location is created, EO is given a name based on address 1, which it uses to create a slug. It does not try to make that slug unique, and so falls over in creating the second location.

However, EO will accept a slug given to it. The fix here, is to generate the WP slug in this plugin, and make sure (mostly!) it is unique by appending the Civi location ID to the end. Belt and braces would then involve checking EO to make sure it really has not been used, but at this stage I think the ID is enough.

So two or more locations with address 1 fields that would result in the same WP slug, will get different WP slugs.

**Comment by judgej** [comment]
On that "misleading" match above, if I create two events with the same `address 1` field, but otherwise a different location, then the second one will be linked to the first instead of resulting in a new and unique location being created. That is probably an edge case, but confused us a little when we were testing (we created a *new* location for a new event in Civi, then found the event on EO linking to a different location).

Like I say, probably edge-case, and some may consider it an advantage, and also there is a workaround to just make sure the `address 1` details are different.

**Comment by judgej** [comment]
Ping @bradydan

**Comment by christianwach** [comment]
Thank you for the detailed explanation and fix. It strikes me, however, that #6 may not be a complete solution for instances where there is an empty "Street Address" field. At present, the code [skips syncing such locations](https://github.com/christianwach/civicrm-event-organiser/blob/406340143022353b3e7b2fad50dfae3ebae6ca50/civicrm-event-organiser-eo-venue.php#L358) but shouldn't. I'll fix that up.

I'd also prefer to add the CiviCRM Location ID to the venue name (and consequently the slug) only if there's a clash, so I think I'll add a check for clashes and apply your fix when there is one. It's an extra hit on the database, but the idea of *always* adding the location ID seems somehow over-cautious to me. I can add a filter to skip that check if you'd prefer to implement your solution directly.

**Comment by bradydan** [comment]
I may be wrong but I thought that with our change the location ID was only added to the URL slug, not the venue name. The `sanitize_title` function is a misnomer, [as the docs say](https://codex.wordpress.org/Function_Reference/sanitize_title): 

> Despite the name of this function, the returned value is intended to be suitable for use in a URL, not as a human-readable title.

**Comment by christianwach** [comment]
> I may be wrong but I thought that with our change the location ID was only added to the URL slug, not the venue name

Dammit, you're quite right. My bad - I misread the code. That'll teach me to review PRs before my coffee's kicked in :-)

I'm still of the opinion that this should only be applied in cases where there's a clash, however. Do you have an opinion on this?

**Comment by bradydan** [comment]
We thought exactly the same and it took a while to find that description (the page I linked to doesn't even include the world 'slug') It's a poorly-named function  :)

If you want to apply it only when there's a clash, I'm fine with that. I'm equally fine with the WP slug always having the Civi location ID, it's a nice human-readable connection of the mapping to Civi, whereas venue titles aren't unique. I doubt (m)any end users are going to notice either way ;)

**Comment by judgej** [comment]
A slug is a slug - make it an md5 and it will still work. `my-place-123` is much more friendlier for publishing (print and email), end users and Google searches though. `my-place` is friendlier still. All good for me - I just ran out of time to do the duplicate checks.

It could also be argued that the problem is really in EO itself - when *it* creates the slug, it does not check for duplicates. So maybe move the solution over there, and then it can be removed here. Or leave it here as a USP over other syncing plugins :smiling_imp: 

Your plugin doesn't care what the slug is, since it does not use it for looking up the location (at the moment), so leaving it with the ID always appended to the slug should keep the binding a little lighter (i.e. EO can do what it likes with the slug - use it, ignore it, replace it, append to it - and the linking will not be affected since you use a custom meta field).

All IMO :-)

**Comment by christianwach** [comment]
Commits dda9d9128c836d8bf78ac2a9817b23e14e313dc3 and 7144ebc54db5e635671c18768605819cb1d9725e implement unique slugs only when there's a clash. You can force your schema by using the filter as documented in 7144ebc54db5e635671c18768605819cb1d9725e. Thanks again for your input.
