### ISSUE TITLE
Plugin conflict - can't add venues to events 

### ISSUE THREAD

**Issue by bradydan** [christianwach/civicrm-event-organiser#7]
When this plugin is activated, adding a venue in the context of editing/creating a regular Events Organiser event is resulting in the following error:

> Are you sure you want to do this?
> Please try again.

The venues are saving, but aren't being related to the event.

(Thinking this was a core Events Organiser issue, I first mentioned this in https://github.com/stephenharris/Event-Organiser/issues/327#issuecomment-176467004 )

**Comment by bradydan** [comment]
ps I updated the plugin to your latest version, following your recent changes. Problem remains.

**Comment by christianwach** [comment]
I see what's causing it - it's the nonce check on my metabox on the venues edit screen kicking in. Will see what I can do.

**Comment by christianwach** [comment]
Should be fixed in 4f64b97d87deef3812320b12e098fd29b3f57aca

**Comment by bradydan** [comment]
Thanks, we'll give that a go

**Comment by bradydan** [comment]
Works :) Thanks for the quick fix
