### ISSUE TITLE
CiviCRM Setting in Event Creation only viewable by capability Access CiviEvent

### ISSUE THREAD

**Issue by danaskallman** [christianwach/civicrm-event-organiser#8]
Is it possible to have the CiviCRM Settings option when adding a new Event in admin or with BP integration plugin only viewable if user has `CiviEvent: access CiviEvent` capability? I have been training a couple of organizations that has staff adding events in WP but don't have Civi access. It's been confusing for users, so would be cool to hide that option if it isn't something they don't have access too.

**Comment by christianwach** [comment]
Hmm, yes, the plugin should respect CiviCRM permissions. I'm not sure how involved a process this would be to implement, but I'll have a look when I get a chance. Thanks for the report!

**Comment by christianwach** [comment]
@danaskallman Does 75790acc0fa77c6523644163b2a40710d8cec1c2 do the trick?

**Comment by danaskallman** [comment]
Yeah, this does the trick. Thanks!
