### ISSUE TITLE
Link to Edit CiviEvent from EO Event

### ISSUE THREAD

**Issue by danaskallman** [christianwach/civicrm-event-organiser#9]
Can a link be added to the CiviEvent settings (maybe front-end view too) to take to edit/add pricing and registration/profile settings for that new event that has been just created or is being edited?

**Comment by christianwach** [comment]
That sounds like a useful addition. Thanks for the suggestion @danaskallman.

**Comment by christianwach** [comment]
@danaskallman In the case of repeating events, which URL would you show? All of them perhaps?

**Comment by danaskallman** [comment]
@christianwach that's a good question. I guess all of them would make sense since you may be looking at the event somewhere in between that series of repeating events.

**Comment by christianwach** [comment]
@danaskallman Sounds reasonable :) I'll have a go at that next.

**Comment by christianwach** [comment]
@danaskallman Please try out the latest master - commit c58caea537dfbd35cf5e18b1592608707fe47b40 is a first pass at adding links to the CiviEvent "Info & Settings" pages for an EO Event. Which other links would be useful?

**Comment by danaskallman** [comment]
hey @christianwach this looks great and works nicely! And yeah, this is so useful, one link access to the event that is synced so I can edit is awesome. 

My only thought/question is can that option be set to appear directly under the Event Options meta box or below below the other CiviCRM EO optoins you have. For me on the site I tested it appears after Excerpt and Custom Fields. So it's not really obvious without scrolling down a ways. Does that make sense?

**Comment by christianwach** [comment]
@danaskallman Vertical placement of metaboxes can be a bit random - there are lots of moving parts. For me the sidebar is quite tall as it is, so I opted for the main column. Latest couple of commits try and place it directly below "Event Options". Let me know if that works for you too.

**Comment by danaskallman** [comment]
@christianwach I figured as much, but had to ask ;) And agreed the sidebar is quite tall already. 

That works perfect!

**Comment by christianwach** [comment]
@danaskallman Good to hear - thanks for the feedback. I'll close this for now but feel free to reopen if you have any further suggestions for the new meta box :-)
